### ISSUE TITLE
May I use this code for the OpenTracing .NET implementation?

### ISSUE THREAD

**Issue by cwe1ss** [serilog/serilog-sinks-periodicbatching#14]
Hi! I'm working on an [opentracing.io](http://opentracing.io) implementation for .NET - a vendor-neutral distributed tracing system. I'm creating base classes for tracer vendors and I'd like to offer some functionality for batched sending. 

The code from this repository would be very helpful so I'm wondering if I may use it? I'd add links/references to here of course!

**Comment by nblumhardt** [comment]
Hi Christian, thanks for reaching out!

The code is provided under the Apache License 2.0 license, so long as the terms of the license are met this is fine.

I am glad to hear the code might solve some problems for you and get some wider usage; I would guess most/all of the contributors here are likely to feel the same way. Let us know how you go!
