### ISSUE TITLE
by design: flush first message 

### ISSUE THREAD

**Issue by ericvb** [serilog/serilog-sinks-periodicbatching#19]
Hi,
When trying to use an other serilog sink, namely serilog-sinks-email, I stumbled on a problem.
Whatever I do, I receive always one email with the first log message and then a second mail with the rest of the same error message types.

The email sink code is based on this sink and I see that 'by design' the first message is always directly sent.
I understand the need when in a "F5" scenario, but with an email scenario I don't want this.
Can this behaviour be overrided?

I find it strange that I don't find any other issues from other people with this same problem.
Am I using the email sink not correctly? (maybe this question is more for the github rep serilog-sinks-email :-) )

**Comment by merbla** [comment]
Thanks @ericvb, I have moved this over to the email sink.  It seems a better home for this issue.

https://github.com/serilog/serilog-sinks-email/issues/47
