### ISSUE TITLE
Option for flush on fatal message

### ISSUE THREAD

**Issue by MartinDemberger** [serilog/serilog-sinks-periodicbatching#20]
I'm using the mail sink to send critical errors. Most of the time the log-messages which describes why my application is killed aren't sent. I guess this is because the server process is killed before the periodic batch is sent.
I think it might be a good idea to give a option like "send fatal messages immediately".

**Comment by splendid25** [comment]
I had the same issue, and solved it by calling Log.CloseAndFlush() just before the process end.

**Comment by nblumhardt** [comment]
Calling `Log.CloseAndFlush()` is the way to go, though there are some ongoing discussions on serilog/serilog regarding some kind of flush mechanism - thanks for the input!
