### ISSUE TITLE
How to use this Nuget

### ISSUE THREAD

**Issue by abolfazlmohammadiseif** [serilog/serilog-sinks-periodicbatching#35]
Hi
How can I use this Nuget? 
What is the configuration?
Thanks

**Comment by nblumhardt** [comment]
This package provides a base class, `PeriodicBatchingSink`, that many other sinks build upon. It's not able to be used directly. HTH!

**Comment by abolfazlmohammadiseif** [comment]
So do you know how to use or enable periodic sink while using `Serilog.Sinks.RabbitMQ`  ? I think it is built upon `PeriodicBatchingSink`. right?

**Comment by nblumhardt** [comment]
It's already used, automatically. There's no way to configure it. See: https://github.com/sonicjolt/serilog-sinks-rabbitmq/blob/development/src/Serilog.Sinks.RabbitMQ/Sinks/RabbitMQ/RabbitMQSink.cs#L27

HTH

**Comment by abolfazlmohammadiseif** [comment]
I Found how to config it. Thanks

**Comment by nblumhardt** [comment]
:+1:
