### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mniak** [serilog/serilog-sinks-periodicbatching#43]
When I use this sink, the CPU consumption increases significantly even without any logs being recorded.

I also found a report of a developer having the same problem: https://github.com/serilog/serilog-sinks-elasticsearch/issues/137

Framework: .NET Core 2.2

**Comment by nblumhardt** [comment]
Hi @mniak - thanks for reaching out.

Can you please "break" your debugger when the problem occurs, and post some details of what threads are in the _Serilog_ assemblies at that point? Would be great to track this down, if it's a Serilog issue 👍 

Your logger configuration (code and/or config) would also help identify/rule out some possibilities.

Thanks!

**Comment by mniak** [comment]
Hi, I finally found the problem, and it is not a bug in the Serilog code.

I will describe it here to help people that can have this same behavior:
I was providing `period` with `TimeSpan.Zero` by accident.

**Comment by mniak** [comment]
It is also worth mention that the code in this repository already has a check for `TimeSpan.Zero` since PR #34. The reason that my code did not report this is because i was using `Serilog.Sinks.PeriodicBatching@2.1.1` as a transitive dependency of `Serilog.Sinks.AzureEventHub@4.1.0`

**Comment by mniak** [comment]
The only thing that still does not make sense for me is why the timer is still on even while there is no remaining messages to be sent in the batch?

I will open a different issue to address this.

Thanks.
