### ISSUE TITLE
Summary for QueueLimit in PeriodicBatchingSinkOptions wrong

### ISSUE THREAD

**Issue by HakanL** [serilog/serilog-sinks-periodicbatching#50]
Says default is 10,000, but it's set to 100,000.
https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSinkOptions.cs#L45

**Comment by nblumhardt** [comment]
Thanks, this is a docs bug, I'll fix in-place 👍
