### ISSUE TITLE
PeriodicBatchingSink Sealed

### ISSUE THREAD

**Issue by aplato** [serilog/serilog-sinks-periodicbatching#69]
The scope was changed again. I was inheriting from PeriodicBatchingSink. Several projects inherit from this class as well. I think this happened in 3.0.0 and was reverted in 3.1.*. 

Is this intended behavior in 4.0 going forward or does it need to be reverted again?/

https://github.com/serilog-contrib/serilog-sinks-elasticsearch/issues/466

**Comment by nblumhardt** [comment]
PR'd a fix for this: https://github.com/serilog-contrib/serilog-sinks-elasticsearch/pull/579 - thanks for the heads-up.

**Comment by nblumhardt** [comment]
PR is merged. Does the latest prerelease build of _Serilog.Sinks.Elasticsearch_ resolve this for you? Cheers!

**Comment by aplato** [comment]
All good. Thank you.

**Comment by Verdurakh** [comment]
I still have the same problem with Serilog.Sinks.Elasticsearch v 9.0.3
and Serilog.Sinks.PeriodicBatching v 4
Serilog v 3.1.1
where the PeriodicBatching is sealed.

what versions should I use to get this resolved?

Thanks

**Comment by nblumhardt** [comment]
Hi @Verdurakh - I'm not sure where the Elastic sink pre-release packages go or what their schedule is, I'm not a maintainer there. Asking over on that repo would be the way to go. HTH!
