### ISSUE TITLE
Missing SourceLink and symbols in nuget package

### ISSUE THREAD

**Issue by tbolon** [serilog/serilog-sinks-periodicbatching#83]
Compare [nuget.info](https://nuget.info/packages/Serilog.Sinks.PeriodicBatching/4.1.1) with the one from [Serilog](https://nuget.info/packages/Serilog/3.1.1).

It's missing at least:

```xml
<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
```

```xml
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

I am not sure the RepositoryUrl and RepositoryType are required when Microsoft.SourceLink.GitHub is referenced.

~~Not sure how the Deterministic flag is set. I was thinking that the IsDeterministic Property should be set in the csproj, but I can't find it in serilog. Maybe it's a flag passed when compiling the release version?~~

~~Maybe you should just set the `/p:ContinuousIntegrationBuild=true` flag when calling msbuild.~~

You already set the ContinuousIntegrationBuild in Build.ps1, I don't know why it's not reflected in the nuget package.

I can submit a PR, but I am not sure I will be able to check the package output from this.

**Comment by bartelink** [comment]
I believe that If you submit a PR, the PR build will generate a package, which you can check with nuget.info
snupkg is pretty optional, especially for things outside of core

**Comment by tbolon** [comment]
Simply adding a reference to SourceLink package did not made the check green, so I added the same properties as the one I found on [serilog project](https://github.com/serilog/serilog/blob/dev/src/Serilog/Serilog.csproj)

**Comment by tbolon** [comment]
> I believe that If you submit a PR, the PR build will generate a package, which you can check with nuget.info snupkg is pretty optional, especially for things outside of core

In my case I have a memory dump from my server with a lot of awaiting tasks linked to periodic batching, even after upgrading to the latest version (used in sinks.seq package). I wanted to track periodicbatching instances and source code, and here I am :) So I won't say it's really optional 😅
